// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgdpezhwwxnsvnepkgcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZHBlemh3d3huc3ZuZXBrZ2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTcyNzksImV4cCI6MjA2NTEzMzI3OX0.nHgA8WI1opYwCCZqda8GEjuqGys93xP8_1p7greYe4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);